### ISSUE TITLE
Hi~

### ISSUE THREAD

**Issue by antfu** [intlify/intlify-core#1]
Hi, I have just read your plan for this project on Medium. And I am really interested in it. I feel the same about your points and I think we can have a better i18n developing the ecosystem. (and that's also the why I made `Vue i18n Ally` more general as `i18n Ally` for bringing everyone's' i18n DX better)

Anyway, I am here for just saying hi and if you gonna start this project, I would love to participate and contribute! Thank you! 🥳

**Comment by kazupon** [comment]
Hi !
Thank you for your interest!

i18n-ally is awesome OSS.
I will invite you to your email.
Please wait! 😉

**Comment by antfu** [comment]
Thank you!
Looking forward for that! 😄
